server:
  port: 5555


validation-url: http://localhost:3010/validateToken

spring:   
  application:
    name: fetchdatabyfilters
  datasource:
    url: jdbc:sqlserver://meeting-room-server.database.windows.net:1433;database=MeetingRoomDB;user=meeting-room-server@meeting-room-server;password=Password#123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: meeting-room-server@meeting-room-server
    password: Password#123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver   
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
      
     